In [1]:
import numpy as np

## Binary Cross Entropy

In [2]:
m = 5 # samples

#### Target variable

In [3]:
Y = np.array([1, 0, 1, 1, 0]).reshape(m, 1)
print(Y.shape)
Y

(5, 1)


array([[1],
       [0],
       [1],
       [1],
       [0]])

#### Predicted Target variable

In [4]:
Y_hat = np.array([0.68, 0.27, 0.27, 0.56, 0.11]).reshape(m, 1)
print(Y_hat.shape)
Y_hat

(5, 1)


array([[0.68],
       [0.27],
       [0.27],
       [0.56],
       [0.11]])

#### Cost Function

In [5]:
loss = -(Y * np.log(Y_hat) + (1 - Y) * np.log(1 - Y_hat))
loss

array([[0.38566248],
       [0.31471074],
       [1.30933332],
       [0.5798185 ],
       [0.11653382]])

In [6]:
cost = np.sum(loss) / m
cost

0.5412117714288682

## Cross Entropy

In [7]:
m = 5 # samples
c = 3 # output classes

#### Target variable

In [8]:
Y = np.array([1, 0, 2, 1, 0])
print(Y.shape)
Y

(5,)


array([1, 0, 2, 1, 0])

#### Encoded Target variable

In [9]:
Y = np.array([[0., 1., 0.], [1., 0., 0.], [0., 0., 1.], [0., 1., 0.], [1., 0., 0.]])
print(Y.shape)
Y

(5, 3)


array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

#### Predicted Target variable

In [10]:
Y_hat = np.array([[0.2, 0.68, 0.12],[0.73, 0.06, 0.15],[0.58, 0.45, 0.27],[0.34, 0.56, 0.09],[0.89, 0.02, 0.6]])
print(Y_hat.shape)
Y_hat

(5, 3)


array([[0.2 , 0.68, 0.12],
       [0.73, 0.06, 0.15],
       [0.58, 0.45, 0.27],
       [0.34, 0.56, 0.09],
       [0.89, 0.02, 0.6 ]])

#### Cost Function

In [11]:
-Y * np.log(Y_hat)

array([[0.        , 0.38566248, 0.        ],
       [0.31471074, 0.        , 0.        ],
       [0.        , 0.        , 1.30933332],
       [0.        , 0.5798185 , 0.        ],
       [0.11653382, 0.        , 0.        ]])

In [12]:
loss = np.sum((-Y * np.log(Y_hat)), axis=1)
loss

array([0.38566248, 0.31471074, 1.30933332, 0.5798185 , 0.11653382])

In [13]:
cost = np.sum(loss) / m
cost

0.5412117714288682